config/routes.rb
Letsmeet::Application.routes.draw do
  get "users/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :meetups
  resources :users
  resources :sessions
  
 root :to => "meetups#signup"
  match 'list' => 'meetups#list'
  match 'pending' => 'meetups#pending'
  match 'upcoming' => 'meetups#upcoming'

end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  has_many :meetupdetails
  has_many :chats
  has_many :users, :through => :meetupdetails
  accepts_nested_attributes_for :meetupdetails, :chats
  attr_accessible  :name, :when, :where, :placename, :user_ids, :createdby, :meetupdetails_attributes, :chats_attributes
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  # GET /meetups
  # GET /meetups.json
  def index
    @meetups = Meetup.joins("LEFT OUTER JOIN meetupdetails ON meetupdetails.meetup_id = meetups.id where meetupdetails.answer is null and 	    meetupdetails.user_id = ", session[:userid].to_s)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetups }
    end
  end
  
    def list
    @meetups = Meetup.joins("LEFT OUTER JOIN meetupdetails ON meetupdetails.meetup_id = meetups.id where meetupdetails.answer = 'Y' and meetupdetails.user_id =", session[:userid].to_s)
    respond_to do |format|
      format.html # list.html.erb
      format.json { render json: @meetups }
    end
  end

  def pending
    @meetups = Meetup.joins("LEFT OUTER JOIN meetupdetails ON meetupdetails.meetup_id = meetups.id where meetupdetails.answer is null and meetupdetails.user_id =", session[:userid].to_s)
    respond_to do |format|
      format.html # list.html.erb
      format.json { render json: @meetups }
    end
  end

    def upcoming
    @meetups = Meetup.joins("LEFT OUTER JOIN meetupdetails ON meetupdetails.meetup_id = meetups.id where meetupdetails.answer = 'Y' and meetupdetails.user_id =", session[:userid].to_s)
    respond_to do |format|
      format.html # list.html.erb
      format.json { render json: @meetups }
    end
  end
   def signup
   @user = User.new
    respond_to do |format|
      format.html # list.html.erb
      format.json { render json: @meetups }
    end
  end
  

# GET /meetups/1
  # GET /meetups/1.json
  def show
    @meetup = Meetup.find(params[:id])
  data = 1
  if(@meetup.createdby.to_s != '')
    data = @meetup.createdby
  end
  @crby = User.find(data)
  @meetup.chats.build 




    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meetup }
    end
  end

  # GET /meetups/new
  # GET /meetups/new.json
  def new
    @meetup = Meetup.new
	@meetup.meetupdetails
	@meetup.meetupdetails.build 
	

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meetup }
    end
  end

  # GET /meetups/1/edit
  def edit
    @meetup = Meetup.find(params[:id])
  end

  # POST /meetups
  # POST /meetups.json
  def create
    @meetup = Meetup.new(params[:meetup])
	@meetup.meetupdetails


    respond_to do |format|
      if @meetup.save

		
		
       

        format.html { redirect_to @meetup, notice: 'Meetup was successfully created.' }
        format.json { render json: @meetup, status: :created, location: @meetup }
      else
        format.html { render action: "new" }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetups/1
  # PUT /meetups/1.json
  def update
    @meetup = Meetup.find(params[:id])

    respond_to do |format|
      if @meetup.update_attributes(params[:meetup])
        format.html { redirect_to @meetup, notice: 'Meetup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetups/1
  # DELETE /meetups/1.json
  def destroy
    @meetup = Meetup.find(params[:id])
    @meetup.destroy

    respond_to do |format|
      format.html { redirect_to meetups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/meetups/_form.html.erb
<div data-theme="d">
<%= form_for(@meetup) do |f| %>
  <% if @meetup.errors.any? %>
				<div id="error_explanation">
				  <h2><%= pluralize(@meetup.errors.count, "error") %> prohibited this meetup from being saved:</h2>

				  <ul>
				  <% @meetup.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				  <% end %>
				  </ul>
				</div>
  <% end %>

  <div class="field">
		   <b> <%= f.label :Name %></b>
			<%= f.text_field :name %>
  </div>

<div class="field">

   <b> <%= f.label :When %></b><br />
	
		 <div class="ui-grid-a">
				
				<div class="ui-block-a">
					  <div class="ui-bar ui-bar-c" style="height:60px">
					  <%= f.date_field :when %>
					  </div>
			   </div>
   
			   <div class="ui-block-b">
			   
				  <div class="ui-bar ui-bar-c" style="height:60px">
			   <!-- This is not getting saved.. -->
			  <input id="Field2-1" name="Field2-1" type="time" class="field text" value="" size="2" maxlength="2" tabindex="2" />
			  
				  </div>
			  </div>
         </div>
 </div>


  <div class="field">
			   <b><%= f.label :Where %></b><br />
				<div id="mapSearchbox"></div>
				 <ul id="results"></ul>
				<%= f.hidden_field :where , :id => "set_location", :value=> "dummy"%>
                <%= f.hidden_field :placename , :id => "set_placename", :value=> ""%>
  </div>
  
  
   <div class="field">
			<b><%= f.label :Friends %></b><br />
		 <%= f.collection_select(:user_ids, User.all, :id, :name,{}, {:multiple => true, :size =>4, :"data-native-menu" => 'false' }) %>



  </div>
 <br>

  <div class="actions">
        <%= f.submit %>
  </div>

<% end %>
</div>

app/views/meetups/edit.html.erb
<h1>Editing meetup</h1>

<%= render 'form' %>

<%= link_to 'Show', @meetup %> |
<%= link_to 'Back', meetups_path %>

app/views/meetups/index-new.html.erb
<div data-role="page" id="home" data-theme="b">

	<div data-role="content">
	
	<div id="branding">
		<h1>Let's meet!</h1>
	</div>
	
	<div class="choice_list"> 
	<h2>Who are you meeting today?</h2>
	
	<ul data-role="listview" data-inset="true" >
	<li><%= link_to image_tag('/events_icon.jpg')+'Upcoming meetups', meetups_path  %></li>
	<li><%= link_to image_tag('/Create_Event.jpg')+'New Meetup', new_meetup_path  %></li>

	</ul>	
	
	</div>
	</div>

</div><!-- /page -->

app/views/meetups/index.html.erb
<div data-role="page" id="home" data-theme="a">

	<div data-role="content" data-theme="a" >
	
		<div data-role="header" data-theme="a"> 
		<h1> Let's meet!</h1>
			</div> 
		
	
	
<img class="main-image" src="5.jpg" />
	
	
	
	<ul data-role="listview" data-inset="true"  data-theme="a">
	<li><%= link_to image_tag('/img_crtRole.gif')+'Pending meetups', '/pending'  %></li>
	<li><%= link_to image_tag('/img_crtStaff.gif')+'Upcoming meetups', '/upcoming'  %></li>
	<li><%= link_to image_tag('/img_crtStudent.gif')+'New Meetup', new_meetup_path  %></li>

	</ul>
	
	<script>
$(function () {
		//establish Pusher connection
		var pusher = new Pusher('005d401511dedbba314f');
		var myChannel = pusher.subscribe('new_invitations');
		myChannel.bind('data-changed', function(data){
			updateResults(data)
		});
	});
	


function updateResults(data){
	$("#invi").html("1 new invitation");
	}
</script>
	</div>
	</div>
</div><!-- /page -->

app/views/meetups/list.html.erb
<h1>Listing meetups</h1>


<table>
  <tr>
    <th>Name</th>
    <th>Where</th>
    <th>When</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetups.each do |meetup| %>
  <tr>
    <td><%= meetup.name %></td>
    <td><%= meetup.where %></td>
    <td><%= meetup.when %></td>
    <td><%= link_to 'Show', meetup %></td>
    <td><%= link_to 'Edit', edit_meetup_path(meetup) %></td>
    <td><%= link_to 'Destroy', meetup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meetup', new_meetup_path %>

<script>
$(function() {
  var pusher = new Pusher('005d401511dedbba314f');
  var channel = pusher.subscribe('my_notifications');
  var notifier = new PusherNotifier(channel);
});
</script>

app/views/meetups/login.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @meetup.name %>
</p>

<p>
 <b>Where:</b> 
   <div id = "meetup_where"> </div>
</p>


<div data-role="collapsible">
    <h4>Map</h4>
<div id="map" style="width: 500px; height: 270px;"></div>
</div>

<p>
  <b>When:</b>
  <%= @meetup.when %>
</p>


<p>
  <b>Who:</b>
  <% @meetup.users.each do |user| %>
  <ul> <%= user.name %> </ul>
  <% end %>
</p>
  <b>Want to say something to the group?</b>

        <div data-role="fieldcontain">
            <textarea name="" id="textarea1" placeholder="" data-mini="true"></textarea>
        </div>
		   <input type="submit" value="Submit">
<script>
	nokia.Settings.set("appId", "_peU-uCkp-j8ovkzFGNU"); 
    nokia.Settings.set("authenticationToken", "gBoUkAMoxoqIWfxWA5DuMQ");
	
		var map = new nokia.maps.map.Display(document.getElementById("map"), {
			// Initial center and zoom level of the map
			zoomLevel: 10, 
			center: [52.51, 13.4],
			components: [new nokia.maps.map.component.Behavior(),
				// Creates UI to easily switch between street map satellite and terrain mapview modes
				new nokia.maps.map.component.TypeSelector(),
				// ZoomBar provides a UI to zoom the map in & out
				new nokia.maps.map.component.ZoomBar(),
				// Add ContextMenu component so we get context menu on right mouse click / long press tap
				new nokia.maps.map.component.ContextMenu()
			]
		});
		
		var place = '<%= raw @meetup.where %>';
		
		//var jsonPlace = JSON.parse(place);
	     var jsonPlace = JSON.parse(place);
		 
		var mapPlaceWidget = new nokia.places.widgets.Place({
			map: map,
			placeId : jsonPlace.placeId
		});

		var placeName = jsonPlace.title;
		$("#meetup_where").html(placeName);


		//alert(jsonPlace);
		//mapPlaceWidget.setPlace({ href: jsonPlace.href });
</script>
<%= link_to 'Edit', edit_meetup_path(@meetup) %> |
<%= link_to 'Back', meetups_path %>

app/views/meetups/login_form.html.erb
<html>

<head>

<link href="Login.css" rel="stylesheet" />
<script type="text/javascript" src="jquery-1.2.6.min.js"></script>
<!--script type="text/javascript" src="jquery.easing.1.3.js"></script--> 

<script language="javascript">
$(document).ready(function() {
	
	$('#nav-bar').fadeIn();
	
	$('#Log-in').click(function() {
		
		$('#Log-in').css('background-color', '#006699');
		$('#signUp').css('background-color', '#000000');
		$('#submit').hide().css({'left' : '0px'});
		$('#SignupForm').hide().css({'top' : '0px'});
		
		$('#loginBtn').show().animate({
		
			down   : '70%',
			
		},400,function(){
			
			$('#loginBtn').css({'-webkit-transform' : 'rotate(-0deg)','-moz-transform' : 'rotate(-0deg)' });
		
		});
		///
		$('#Login_form').show().animate({
	
			top   : '60px',
			
		},700,function(){
			
			//$('#image').css({'-webkit-transform' : 'rotate(-90deg)','-moz-transform' : 'rotate(-90deg)' });
		});
	});
	
	$('#signUp').click(function() {
		
		$('#signUp').css('background-color', '#006699');
		$('#Log-in').css('background-color', '#000000');
		$('#loginBtn').hide();
		$('#Login_form').hide().css({'top' : '0px'});
		
		$('#submit').show().animate({
		
			down   : '70%',
			
		},400,function(){
			
			$('#submit').css({'-webkit-transform' : 'rotate(-0deg)','-moz-transform' : 'rotate(-0deg)' });
		
		});
		///
		$('#SignupForm').show().animate({
	
			top   : '60px',
			
		},700,function(){
			
			//$('#image').css({'-webkit-transform' : 'rotate(-90deg)','-moz-transform' : 'rotate(-90deg)' });
		});
	});
	
});
</script>
</head>
<body>

	<img src="result.png" id="loginBtn" />	
	<img src="submit.png" id="submit" />

	<div class="loginform" id="Login_form">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this meetup from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Username %><br />
    <%= f.text_field :username %>
  </div>

   <div class="field">
    <%= f.label :Password %><br />
    <%= f.text_field :password %>
  </div>
 
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</body>
</html>

app/views/meetups/new.html.erb
<div data-role="header" data-theme="a"> 
		<h1>New Meet Up</h1>
	</div> 
<br>
<br>
<%= render 'form' %>



<script>
$(function() {
  var pusher = new Pusher('005d401511dedbba314f');
  var channel = pusher.subscribe('my_notifications');
  var notifier = new PusherNotifier(channel);
});
</script>

 <script>
	//nokia.Settings.set("appId", "qIcfxFqGXIbUXS3h1DRr"); 
    //nokia.Settings.set("authenticationToken", "UphMryg8D56qK6jW5oHKUg");
	var lat;
	var lon;
	if (navigator.geolocation)
    {
	 navigator.geolocation.getCurrentPosition(showPosition);
	}
	
	function showPosition(position)
    {
		lat = position.coords.latitude;
        lon = position.coords.longitude;
    }
	
	nokia.Settings.set("appId", "_peU-uCkp-j8ovkzFGNU"); 
    nokia.Settings.set("authenticationToken", "gBoUkAMoxoqIWfxWA5DuMQ");
	

	    var resultList = new nokia.places.widgets.ResultList ({
        targetNode: 'results',
        perPage: 1,
        events: [{
            rel: 'nokia-place-name',
            name: 'click',
            handler: function (jsonObj) {
                var pp = new nokia.places.Place ({
                    placeId: jsonObj.placeId,
                    targetNode: 'detail'
                });
            }
        }]
    });

	var sb = new nokia.places.widgets.SearchBox({
    targetNode: 'mapSearchbox',
	 searchCenter: function () {
            return {
                latitude: lat,
                longitude: lon
            }
	  },
    onResults: function (data) {
	            resultList.setData(data);
	var sel = resultList.getCurrentPageData();
	$("#set_location:hidden").val(JSON.stringify(sel[0]));
	$("#set_placename:hidden").val(sel[0].title);


    }  
});


   </script>

app/views/meetups/new1.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/meetups/pending.html.erb
<!DOCTYPE html> 
<html> 
<head> 
	<meta charset="UTF-8">
	<title>Upcoming Events</title> 
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<link rel="stylesheet" href="jquery.mobile.structure-1.0.1.css" />
	<link rel="apple-touch-icon" href="images/launch_icon_57.png" />
	<link rel="apple-touch-icon" sizes="72x72" href="images/launch_icon_72.png" />
	<link rel="apple-touch-icon" sizes="114x114" href="images/launch_icon_114.png" />
	<link rel="stylesheet" href="jquery.mobile-1.0.1.css" />
	<!--<link rel="stylesheet" href="custom.css" />-->
	<script src="js/jquery-1.7.1.min.js"></script>
	<script src="js/jquery.mobile-1.0.1.min.js"></script>
</head> 
<body> 
<div  data-theme="a" data-role="page">
	
	<div data-role="header"  data-theme="a" > 
		<h1> Pending Events</h1>
	</div> 
      <br>
	  <br>
	<div data-role="content">
	


	<div class="choice_list"> 
	
		<% @meetups.each do |meetup| %>
	<ul data-role="listview" data-inset="true" >
	<!--<li><a href="show_event.html" data-transition="slidedown"> <img src="pending_event.jpg"/> <h2> Party Tonight</h2> </a></li>
	<li><a href="show_event.html" data-transition="slidedown"> <img src="pending_event.jpg"/> <h2> Cafe Coffee Day  </h2> </a></li>
	<li><a href="show_event.html" data-transition="slidedown"> <img src="pending_event.jpg"/> <h2> Lunch @ Infusion </h2> </a></li>-->
		<li><%= link_to image_tag('/img_crtRole.gif')+meetup.name, meetup  %></li>
	
	</ul>	
	
	    <% end %>
	
	</div>

	</div>

</div><!-- /page -->
</body>
</html>

app/views/meetups/show.html.erb
<div data-role="content" data-theme="a">


 <div  data-role="header" data-theme="a">
        <h3>
         <b>   <%= @meetup.name %></b>
        </h3>
    </div>  
 <br>
 <br>

 <div data-theme="a" class="ui-grid-a" >
<div class="ui-bar ui-bar-a"><p><b>Organized by:</b> 
  <%= @crby.name %>
  </p>
  </div>

  </div>
  <br>


<div class="ui-grid-a">
    <div class="ui-block-a"><div class="ui-bar ui-bar-a"><p>
 <b>Where :</b>   <%= @meetup.placename%>

</p></div></div>
    <div class="ui-block-b"><div class="ui-bar ui-bar-a" >
	
<p>
  <b>When:</b>
  <%= @meetup.when %>
</p>
	
	</div></div>
</div>
<br>
<div data-role="collapsible">
    <h4>Map</h4>
<div id="map" style="width: 500px; height: 270px;"></div>

<!-- Share location -->
 <%= form_for  @meetup  do |f| %>
		 <% @meetup.meetupdetails.each do |m| %>
		  <% if m.user_id == session[:userid].to_i  %>
			<%= f.fields_for :meetupdetails, m do |m_f| %>
			   <%= m_f.hidden_field :lat, :id => "lt", :value => "12.98" %> 
			   <%= m_f.hidden_field :long, :id => "ln", :value => "77.58"%> 
			<% end %>
		  <% end %>
		<% end %>
	<%= f.submit "Share my location"%> 
<% end %>
</div>

<br>
 
 <div id ="update-friends">
 <p><b>Who?</b></p><br>
  <% @meetup.meetupdetails.each do |m| %>
  <ul> <img src="<%= m.user.pic %>"> <%= m.user.name %> says :  <img src="/<%= m.answer %>_i.JPG"/></ul>
  <% end %>
</div>
<br>

<div data-role="collapsible">
    <h4>Are you going?</h4>
  	
			
			<div class="ui-grid-a">
			<div class="ui-block-a"><div class="ui-bar ui-bar-c" style="height:60px"><p>
			
			  <%= form_for  @meetup do |f| %>
		 <% @meetup.meetupdetails.each do |m| %>
		  <% if m.user_id == session[:userid].to_i %>
			<%= f.fields_for :meetupdetails, m do |m_f| %>
							<%= m_f.hidden_field :answer , :value=> "Y"%>
			  			  	<%= f.submit "Yes, I'm in!"%> 

			<% end %>
		  <% end %>
		<% end %>
	<% end %>

			</div></div>
    <div class="ui-block-b"><div class="ui-bar ui-bar-c" style="height:60px">
	
		  <%= form_for  @meetup do |f| %>
		 <% @meetup.meetupdetails.each do |m| %>
		  <% if m.user_id == session[:userid].to_i  %>
			<%= f.fields_for :meetupdetails, m do |m_f| %>
				<%= m_f.hidden_field :answer , :value=> "N"%>
			<%= f.submit "Sorry can't make it"%> 
			<% end %>
		  <% end %>
		<% end %>
	<% end %>
	
	
	</div></div>
</div>
			



</div>
<br>


<div id ="chat">


<%= form_for @meetup do |f| %>
<h2><b>Say something.......</b></h2><br>
<% @meetup.chats.each do |ch| %>
 <% if ch.user_id.to_s != '' %>
 <ul><img src="<%= User.find(ch.user_id).pic %>"> <%= User.find(ch.user_id).name %> says : <%=ch.content %> </ul>
 <% end %>
<% end %>
<% @meetup.chats.each do |c| %>
    <% if c.content.to_s == '' %>
      <%= f.fields_for :chats, c do |c_f| %>
	   <%= c_f.text_field :content ,:required => true %>
	   	<%= c_f.hidden_field :user_id , :id => "user_id", :value=> session[:userid]%>
	  <% end %> 
	<% end %> 
 <% end %>
 	<%= f.submit "Send"%> 
<% end %>
</div>

<div data-role="footer" class="ui-bar" data-theme="a">
    <a href="#" data-icon="twitter">Twitter</a>
    <a href="#" data-icon="facebook">Facebook</a>
</div>
		   
		   

<script>

  //set blore as default
                var lat = 12.98;
                var long = 77.58;
$(document).ready(function() {
     navigator.geolocation.getCurrentPosition(
             onSuccess,
             onError, {
                 enableHighAccuracy: true,
                 timeout: 20000,
                 maximumAge: 120000
             }
     );
                
   function onSuccess(position) {
                                lat = position.coords.latitude;
                                long = position.coords.longitude;
                                $('#lt').val(position.coords.latitude);
                                $('#ln').val(position.coords.longitude);
   }
   
   function onError(err) {
       var message;

       switch (err.code) {
       case 0:
         message = 'Unknown error: ' + err.message;
         break;
       case 1:
         message = 'You denied permission to retrieve a position.';
         break;
       case 2:
         message = 'The browser was unable to determine a position: ' + error.message;
         break;
       case 3:
         message = 'The browser timed out before retrieving the position.';
         break;
       }
    }

});


                                nokia.Settings.set("appId", "_peU-uCkp-j8ovkzFGNU"); 
        nokia.Settings.set("authenticationToken", "gBoUkAMoxoqIWfxWA5DuMQ");
                                var map = new nokia.maps.map.Display(document.getElementById("map"), {
                                                // Initial center and zoom level of the map
                                                zoomLevel: 10, 
                                                center: [12.98, 77.58],
                                                components: [new nokia.maps.map.component.Behavior(),
                                                                // Creates UI to easily switch between street map satellite and terrain mapview modes
                                                                new nokia.maps.map.component.TypeSelector(),
                                                                // ZoomBar provides a UI to zoom the map in & out
                                                                new nokia.maps.map.component.ZoomBar(),
                                                                // Add ContextMenu component so we get context menu on right mouse click / long press tap
                                                                new nokia.maps.map.component.ContextMenu()
                                                ]
                                });
                                
                                var place = '<%= raw @meetup.where %>';
                                
                                //var jsonPlace = JSON.parse(place);
                     var jsonPlace = JSON.parse(place);
                                
                                var mapPlaceWidget = new nokia.places.widgets.Place({
                                                map: map,
                                                placeId : jsonPlace.placeId
                                });

                                var placeName = jsonPlace.title;
                                $("#meetup_where").html(placeName);

                                //also mark the destination
                                
                                var dest = new nokia.maps.map.StandardMarker([jsonPlace.position.latitude, jsonPlace.position.longitude], {
                                text: placeName,
                                textPen: {
                                                                strokeColor: "#333"
                                                }
                                });

                                map.objects.add(dest);

                <% @meetup.meetupdetails.each do |m| %>
                                var lati = 40.42;
                                var longi = 98.73;
                                <% if m.lat.to_s != '' %>
                                  lati = <%= m.lat %>;
                                <% end %>
                                <% if m.long.to_s != '' %>
                                  longi = <%= m.long %>;
                                <% end %>
                                var marker = new nokia.maps.map.StandardMarker([lati,longi], {
                                text: "<%=User.find(m.user_id).name %>", 
                                brush: {
                                                                color: "#F80"
                                                },
                                textPen: {
                                                                strokeColor: "#333"
                                                }
                                });

                                map.objects.add(marker);
                                <% end %>
</script>

</div>

app/views/meetups/signup.html.erb
<table width=100% height=100%>
<tr>
<td style="text-align: center; vertical-align: middle;">
<img src="logo.jpg"" />
</td>
</tr>
</table>





<div id="user_nav"  data-theme="a"> 
  <% if current_user %>
   
<div data-role="header"  data-theme="a">   
		<h1>Log In</h1>
	</div>     



<%= form_tag sessions_path do  %>
  <p  class="field">
   <b> <%= label_tag :Username %></b>
    <%= text_field_tag :name, current_user.name %>
  </p>
  <p  class="field">
   <b> <%= label_tag :Password %></b>
    <%= password_field_tag :password, current_user.password %>
  </p>
  <br>

  <p class="button"><%= submit_tag "Log in" %></p>
<% end %>



  <% else %>
    <%= link_to "Sign up", sign_up_path,  { :class => "TopButtons"} %> 
    <%= link_to "log in", log_in_path , { :class => "TopButtons"} %>
  <% end %>
</div>

app/views/meetups/upcoming.html.erb
<!DOCTYPE html> 
<html> 
<head> 
	<meta charset="UTF-8">
	<title>Upcoming Events</title> 
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<link rel="stylesheet" href="jquery.mobile.structure-1.0.1.css" />
	<link rel="apple-touch-icon" href="images/launch_icon_57.png" />
	<link rel="apple-touch-icon" sizes="72x72" href="images/launch_icon_72.png" />
	<link rel="apple-touch-icon" sizes="114x114" href="images/launch_icon_114.png" />
	<link rel="stylesheet" href="jquery.mobile-1.0.1.css" />
	<!--<link rel="stylesheet" href="custom.css" />-->
	<script src="js/jquery-1.7.1.min.js"></script>
	<script src="js/jquery.mobile-1.0.1.min.js"></script>
</head> 
<body> 
<div  data-role="page" data-theme="a">
	
	<div data-role="header"  data-theme="a">   
		<h1>Upcoming MeetUps</h1>
	</div> 

	<div data-role="content"  data-theme="a">
	
	<div class="choice_list"  data-theme="a"> 
	
		<% @meetups.each do |meetup| %>
	<ul data-role="listview" data-inset="true" >
	<!--<li><a href="show_event.html" data-transition="slidedown"> <img src="pending_event.jpg"/> <h2> Party Tonight</h2> </a></li>
	<li><a href="show_event.html" data-transition="slidedown"> <img src="pending_event.jpg"/> <h2> Cafe Coffee Day  </h2> </a></li>
	<li><a href="show_event.html" data-transition="slidedown"> <img src="pending_event.jpg"/> <h2> Lunch @ Infusion </h2> </a></li>-->
		<li><%= link_to image_tag('/img_crtStaff.gif')+meetup.name, meetup  %></li>
	
	</ul>	
	
	    <% end %>
	
	</div>
	</div>
	

</div><!-- /page -->
</body>
</html>